server:
  port: 8085
  servlet:
    context-path: /SHOPCART
    encoding:
      force-response: true
      charset: utf-8

spring:
  #Local
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:db2://scdbesrvb.sc.pt:50000/SHOPCART
    username: db2inst1
    password: db2admin
    driver-class-name: com.ibm.db2.jcc.DB2Driver

  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  #request size
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true
  display-request-duration: true
  filter: true

# loggin config file by profile
log4j:
  configuration:
    path: log4j-local.properties

#Ficheiro de configuracao da SC
sc:
  config:
<<<<<<< HEAD
    file: "/home/ronald/Documents/rigor/repos/S4/shopcart/src/main/resources/sc_config.properties"
=======
    file: "C:/Users/Luis Parra/OneDrive - Rigor/Documentos/REPOSITORIOS/Proyectos GITHUB/shopcart/src/main/resources/sc_config.properties"
>>>>>>> 0e2d2c2970c80620abd7cfae28cc259181a24675

#customom properties ex local url
app:
  baseUrl: /cart
  server:
    type: 10
  auth:
    token-name: accessToken
  datasource:
    first:
      url: jdbc:db2://scdbesrva.sc.pt:50000/DBDMV
      username: db2inst1
      password: db2admin
      driver-class-name: com.ibm.db2.jcc.DB2Driver
    second:
      url: jdbc:db2://scdbesrvb.sc.pt:50000/USRLOGON
      username: db2inst1
      password: db2admin
      driver-class-name: com.ibm.db2.jcc.DB2Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG



